### ISSUE TITLE
User.ROLE error when creating user

### ISSUE THREAD

**Issue by Denesian** [roda0313/SWEN-344-API#27]
Returns "Unable to execute statement: NOT NULL constraint failed: User.ROLE" when trying to create user with all parameters (including user role)

**Comment by ZacharyMoran** [comment]
could you be more specific with the context? i might be able to help

**Comment by roda0313** [comment]
that error means you are missing a parameter

**Comment by roda0313** [comment]
Oh i know what the problem is, I will submit a fix give me a few minutes

**Comment by roda0313** [comment]
It works for me, i re pulled on the VM and recreated the DB schema
