### ISSUE TITLE
Table Classroom does not exist

### ISSUE THREAD

**Issue by roda0313** [roda0313/SWEN-344-API#42]
@Denesian

**Comment by ZacharyMoran** [comment]
/* Classroom Table */
CREATE TABLE Classroom(
	ID INTEGER PRIMARY KEY,
	CAPACITY INTEGER NOT NULL,
	ROOM_NUM INTEGER NOT NULL,
	BUILDING_NUM INTEGER NOT NULL,
);

Its in the facilities management one?

**Comment by roda0313** [comment]
Oh the issue is that it's not creating the table because the syntax is invalid. The comma on the last line needs to not be there. Weird that the createDB script threw no errors
