### ISSUE TITLE
Sql Error in TeamFacilityManagement.sql 

### ISSUE THREAD

**Issue by roda0313** [roda0313/SWEN-344-API#84]
@axv3658 

`INSERT INTO Timeslot (START_TIME)
VALUES
(time('08:00')), (time('09:00')), (time('10:00')), (time('11:00')), (time('12:00')), (time('13:00')), (time('14:00')), (time('15:00')), (time('16:00')), (time('17:00')), (time('18:00')), (time('19:00')), (time('20:00'));`

I just noticed this, this doesn't work. You are only specifying an input of one column then passing in many, many columns

See line 24 in TeamFacilityManagement.sql

**Comment by nns3455** [comment]
This is valid SQL syntax and works when I set up the db on my local machine. I'm not passing in multiple columns, but one column multiple times (once per row that is being added): https://www.quora.com/Can-I-insert-multiple-rows-in-one-query-in-SQL

**Comment by roda0313** [comment]
Yeah this seems weird. The data seems to be reading in correctly on the VM but when i was running some tests and tried to read this file on my personal machine it caused errors. I will close this issue for now since it seems to be working for most people
